### ISSUE TITLE
Invalidate cookie when the same user login from another browser

### ISSUE THREAD

**Issue by franktominc** [setusoft/silhouette-play-react-seed#19]
Hi, how can I invalidate the cookie the user used to sign-in when he login using another browser window(incognito mode, for example).

**Comment by akkie** [comment]
Expect a user is signed in the application, then:

* If you switch to incognito mode, then the browser should normally start fresh without existing cookies -> user must login again
* If the user uses another browser then every browser uses different cookies -> user must login again
* If a user opens a new tab in the same browser then the existing cookie will be used -> user is logged in

Does this answer your question?

**Comment by franktominc** [comment]
No. I'll try to rephrase my question, suppose a user is signed in on browser 1. If the same credentials are used again on another browser(browser 2), the cookie that was used to authenticate the user on browser 1 should be no longer valid. TLDR: One user shouldn't be allowed to use more than one browser at the same time. How can I invalidate the token if the user sign in using another browser?

**Comment by akkie** [comment]
You can use the [stateful cookie authenticator](https://www.silhouette.rocks/docs/authenticator#section-cookieauthenticator) approach. To enable a stateful authenticator you must pass a [AuthenticatorRepository](https://github.com/mohiva/play-silhouette/blob/0b32a4816f56dadf43c53a356a0601a96fe76c36/silhouette/app/com/mohiva/play/silhouette/api/repositories/AuthenticatorRepository.scala) implementation to the authenticator service during instantiation.

In the [add](https://github.com/mohiva/play-silhouette/blob/0b32a4816f56dadf43c53a356a0601a96fe76c36/silhouette/app/com/mohiva/play/silhouette/api/repositories/AuthenticatorRepository.scala#L43) method of your `AuthenticatorRepository` implementation you could then invalidate all stored authenticators for the `LoginInfo` stored in the passed authenticators.

**Comment by akkie** [comment]
@franktominc Does this answer your question? I'll close this mow, because it's a question and not an issue. I'll create a gitter channel, which is better suited for questions.
