### ISSUE TITLE
React-redux-form intialState doesn't load

### ISSUE THREAD

**Issue by orar** [setusoft/silhouette-play-react-seed#36]
I been using silhouette all the time but new to React and have been trying out with this seed and its smooth, great. I have created another module `/route/Front` following the Auth structure and everything is working out except that `react-redux-form.Control` only doesn't load initial values in the initialFormState in any component of `Front`. I have tried initial form values in `SignInModule` for `SignInComponent` from Auth and it works as expected. 
Also Control renders in `Front` as an uncontrolled component  but not in Auth and works as expected as like in any component in `Auth`. 
Is there anything that i can't figure out?

**Comment by akkie** [comment]
Could you please share a link to a repository? It's hard to find a solution without seeing some code.

**Comment by orar** [comment]
Wow, Akkie thanks. Im  replicating the issue. A moment.

**Comment by orar** [comment]
This is the [Component](https://github.com/orar/silhouette-play-react-seed/blob/master/app-ui/src/routes/Front/components/Material/Material.jsx). The `firstName` text input is a basic Control.text but renders as an uncontrolled component. It has an [initial value](https://github.com/orar/silhouette-play-react-seed/blob/master/app-ui/src/routes/Front/modules/MaterialModule.js#L24) but doesn't load the value. Same as the other decorated components.
I checked the `FormProps` `value` field and it contains the initial value.
I have been trying to follow strict the `Auth` module structure.

**Comment by orar** [comment]
![screenshot from 2017-12-08 12-13-36](https://user-images.githubusercontent.com/15624939/33765606-8cde50b8-dc11-11e7-8f6b-f67a3e99804f.png)

**Comment by akkie** [comment]
@orar 

Your [model path](https://github.com/orar/silhouette-play-react-seed/blob/master/app-ui/src/routes/Front/modules/MaterialModule.js#L18) is wrong. You define it as `data` but you use [model](https://github.com/orar/silhouette-play-react-seed/blob/master/app-ui/src/routes/Front/modules/MaterialModule.js#L38). So in your case you must either change the path `front.material.data` to `front.material.model` or you rename your reducer property from `model` to `data`.

**Comment by orar** [comment]
Yeah right. Incredible that i never noticed something simple but did for complex stuff. This shouldn't have been an issue.
