### ISSUE TITLE
java.lang.ClassNotFoundException on sbt 1.0.4

### ISSUE THREAD

**Issue by tododo** [setusoft/silhouette-play-react-seed#37]
Got below error when I ran sbt run. It's resolved when I switched to 1.0.3.
[error] Caused by: java.lang.ClassNotFoundException: org.apache.ivy.core.module.id.ModuleRevisionId
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at sbt.Keys$.<init>(Keys.scala:417)
[error] 	at sbt.Keys$.<clinit>(Keys.scala)
[error] 	at sbt.Cross$.$anonfun$requireSession$1(Cross.scala:75)
[error] 	at sbt.Command$.$anonfun$applyEffect$3(Command.scala:125)
[error] 	at sbt.Command$.$anonfun$combine$2(Command.scala:130)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.immutable.List.map(List.scala:295)
[error] 	at sbt.Command$.$anonfun$combine$1(Command.scala:130)

**Comment by orar** [comment]
Can you paste the full error stack?

**Comment by akkie** [comment]
I've not any issue with SBT 1.0.4. Maybe it's local issue with your ivy repository? Have you tried to remove the repository?

**Comment by tododo** [comment]
I think it's because I have multiple versions of sbt installed on my MacBook pro. I found that this error would occur on certain directories. I am fine when execute sbt sbtVersion under my home directory, but it would occur the same error in other directory. 

Not familiar with sbt, but it seems there is some mechanism caused sourcing of "sbt" command to different version under different directory. And

**Comment by akkie** [comment]
@tododo The project itself comes bundled with a SBT runner that can be used instead of a global installed SBT.

You must only call `scripts/sbt.sh` instead of your global installed sbt. Then it uses the SBT version defined for this project.

I'll close this issue because it's not an issue with the project itself.
