### ISSUE TITLE
i18n error in production

### ISSUE THREAD

**Issue by orar** [setusoft/silhouette-play-react-seed#42]
I run `sbt clean stage && bash target/universal/stage/bin/silhouette-play-react-seed -Dplay.http.secret.key=abcdefghijk` given in the readme.md and it compiled fine as usual but there is a problem with i18n asset in the asset package.
Path: 
`target/universal/stage/lib/your.organisation.silhouette-play-react-seed-5.0.0-assets.jar`
Error: 
` a.a.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Illegal request-target: Invalid input '[', expected pchar, '/', '?' or 'EOI' (line 1, column 17): /assets/ui/i18n-[index].e933c13ab81716562c60.js`
         
Content of [/assets/ui/i18n-[index].e933c13ab81716562c60.js](https://gist.github.com/orar/c074436b372132bee914a3ed37f97e81)

**Comment by akkie** [comment]
@orar Thanks for reporting this issue :+1:  It's fixed with #43
