### ISSUE TITLE
How to inject Silhouette environment into 'app-admin' module

### ISSUE THREAD

**Issue by mrwillis** [setusoft/silhouette-play-react-seed#46]
Hi,

I noticed that this project has a place for you to put your own code, namely in `app-admin`. I noticed that it's another module and thus needs to handle its own injection. My question is how can I get the silhouette environment created in the `auth` module in into my `admin`? Should I just follow the pattern and use Guice to make a new one?

Thanks.

**Comment by akkie** [comment]
@Enalmada Thanks for the great feedback! I share your concerns, but the limiting factor here is time. The project is open to contributions.

In a current project I develop for my employer, I have moved most of the Silhouette bindings, dependencies and configuration into the core project. So it's easier to share it between the other projects. @mrwillis You should do the same.

**Comment by mrwillis** [comment]
Thanks akkie. That seems like a sensible idea. I will try that
