### ISSUE TITLE
User language detection

### ISSUE THREAD

**Issue by Enalmada** [setusoft/silhouette-play-react-seed#47]
My project serves multiple languages so seeing international support in this sample really tipped me over the edge to try it.  When I started it up, it was not in English despite my browser is set "english".  I can see that there seems to be english message capability in the code, so I am just a bit concerned at how the language detection works for users around the world.

My Chrome browser is probably sending en-US and I am just guessing that this project is hardcoded to look for something else but I couldn't find it.   Thoughts?

**Comment by akkie** [comment]
The default language is hard coded in the [I18nModule](https://github.com/setusoft/silhouette-play-react-seed/blob/master/app-ui/src/modules/I18nModule.js#L5).

In JS you can get the user language with:

```
navigator.language || navigator.userLanguage
```

So you have multiple possibilities to change the language:
- Set the language directly in your I18nModule
- Send a `setLanguage` action from anyware from your code
- Provide a dropdown/buttons with languages and dispatch a `setLanguage` action based on the selected language

Based on the selected front end implementation, an `Accept-Language` header  must also be propagated to the backend.
