### ISSUE TITLE
Front-end project architecture questions

### ISSUE THREAD

**Issue by mrwillis** [setusoft/silhouette-play-react-seed#48]
Hi,

Awesome template. I have some questions about the structure of the front-end and the rationale behind the architecture. I see you have a main modules folder which I'm guessing holds top-level redux related stuff. Then you have a folder for each 'bundle', which seems like logical groupings of different functionality (auth, the admin part), etc. Is the idea here that the bundles are injected (reducers, sagas) as they are created into the main saga and store? 

My second question is related to the UserAPI. I notice the front-end top level has a `UserAPI` file in `apis`. Why is this separated from the APIs in the `Auth` module? Should this not also be in the `Auth` module? This is the class I'm referring to.

```js
export default class UserAPI extends API {
  /**
   * Gets a user.
   *
   * @returns An object indicating if the process was successful or not.
   */
  async get(): Promise<APIResponse> {
    const response = await this.request('api/auth/user');

    return response.json();
  }

  /**
   * Sign out a user.
   *
   * @returns An object indicating if the process was successful or not.
   */
  async signOut(): Promise<APIResponse> {
    const response = await this.request('api/auth/sign-out');

    return response.json();
  }
}
```

Thank you for this work!

**Comment by akkie** [comment]
Hi,

you're welcome!

The template uses [Webpack code splitting](https://webpack.js.org/guides/code-splitting/). This means that bundles will be loaded lazy. Please see also: https://github.com/smooth-code/loadable-components

To your second question. This is a consequence of the previous point. The logout mechanism as well as the loading of the user data should be work independent from another bundle. Therefore the functionality is implemented globally. As example: If a user is already signed in (remember-me cookie), then the app do not need to load the auth bundle.

Cheers,
Christian

**Comment by akkie** [comment]
If you have more questions, it would be great if you could use the [forum](http://discourse.silhouette.rocks/).
