### ISSUE TITLE
React goes for maintenance in offline mode

### ISSUE THREAD

**Issue by orar** [setusoft/silhouette-play-react-seed#58]
The current relation of Health and Maintenance is health pulls from api and sets its `isHealthy` status to  `true` or `false`. This contributes to causing maintenance mode. 
- If api response is unhealthy, (`isHealthy: false`), app goes for maintenance. That's fine.
If app goes offline, api response is not justified at that moment but an unhealthy action is issued which puts the app into maintenance mode.

Currently there are only 3 reducer actions for `HealthModule`: `fetchHealth`(`Pending`, `Fulfilled`, `Rejected`).

I add a fourth neutral action (`fetchHealthFailed`) which only sets healthy `isPending` state to `false` without altering the `isHealthy` status if response cannot be justified until connection is restored or app closed to cancel health polling.

Can start React app without Play server or simulate browser offline to reproduce.

**Comment by akkie** [comment]
> If app goes offline, api response is not justified at that moment but an unhealthy action is issued which puts the app into maintenance mode.

This is the desired behavior. If the backend goes down, then the frontend cannot work properly. So it goes in maintenance mode.

**Comment by orar** [comment]
If Play is down, all functionalities of app are seized. This behavior will be least manifested by network partitioning or transient offline based on several network issues. I think it can be enhanced (maybe with retries or counter) a little to make concrete justification.

I'm closing this for now.
